version: '3'
services:
  web:
    container_name: csvserver 
    image: infracloudio/csvserver:latest
    ports:
    - "9393:9300"
    environment:
    - CSVSERVER_BORDER=Orange
    volumes:
      - ${PWD}/inputFile:/csvserver/inputdata
